infrastructure:
  form: ap
  interfaces:
    eth0:
      mac: "40:ed:00:6f:f9:d4"

env:
  interfaces:
    eth0:
      ip: 192.168.10.9
      purpose: mgmt
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
        cnames: []
