infrastructure:
  form: rt
  interfaces:
    eth0:
      mac: "00:e0:4c:29:1e:50"   # re0 LAN
    eth1:
      mac: "00:e0:4c:29:1e:4f"   # re1 WAN

env:
  role: core
  interfaces:
    eth0:
      ip: 192.168.10.1
      purpose: lan
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
        cnames:
          - dns
          - dhcp
          - gateway
    eth1:
      ip: dhcp
      purpose: wan
