infrastructure:
  form: pi
  interfaces:
    eth0:
      mac: "dc:a6:32:c5:a0:c5"

env:
  interfaces:
    eth0:
      ip: 192.168.10.12
      purpose: mgmt
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
