infrastructure:
  form: vm
  interfaces:
    eth0:
      mac: "bc:24:11:f0:e4:68"

env:
  role: provisioner
  interfaces:
    eth0:
      ip: 192.168.10.90
      purpose: mgmt
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
        cnames: []
        pxe_boot:
          tftp_server: "192.168.10.95"
          boot_file: "pxelinux.0"
