infrastructure:
  form: vm
  interfaces:
    eth0:
      mac: "bc:24:11:dc:2a:24"

env:
  role: provisioner
  interfaces:
    eth0:
      ip: 192.168.10.96
      purpose: mgmt
      segment: management
      dns:
        host_a_record: true
        dhcp_reservation: true
        cnames: []
